Add referrer to global ratings survey
springernature/frontend-toolkits pull request #843
Opened 2022-11-07 16:01 UTC by dsmr

Adds a method to the Global Ratings Survey class to allow us to append the user's window.location.href to Survey Monkey links as a custom variable

2022-11-07 16:14 UTC, benjclark commented
Diana and I paired on this 🙂

2022-11-07 17:06 UTC, jpw requested changes
A few things to be looked-at please, thanks 🙂

2022-11-07 17:06 UTC, jpw commented on toolkits/global/packages/global-ratings-survey/view/ratingsSurvey.hbs
> +						<a href="{{questionUrl}}" data-ratings-survey="survey-link" target="_blank">{{questionText}} (opens in a new tab)</a>
Links to external sites must have `rel="noopener"` [added for security reasons](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener) even though [browser support for implied `noopener` behaviour if opening links in new tabs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility) is pretty good.

2022-11-08 16:44 UTC, jpw approved these changes

2022-11-08 16:45 UTC, jpw commented
Good stuff, thank you 🚀

2022-11-09 09:55 UTC, merged